pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Checkout SCM') {
            steps {
                echo '> Checking out the source control ...'
                checkout scm
            }
        }
        stage('Docker Image Build') {
            steps {
                sh 'docker build -t hello:latest .'
            }
        }
        stage('Docker Image Push') {
            steps {
                echo '> Pushing the docker image ...'
            }
        }
    }
}
